name: CI on pull request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate dataset
        run: |
          mkdir data
          python util/generate.py

      - name: Create models directory
        run: mkdir models

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests.py \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            --cov=com --cov-report=xml --cov-report=html
